### ISSUE TITLE
Configuration caching problem

### ISSUE THREAD

**Issue by plnice** [littlerobots/version-catalog-update-plugin#16]
Steps to reproduce:
1. Attach plugin (tested version 0.2.2) to the project that is based on Gradle 7.3.3 and has `org.gradle.unsafe.configuration-cache=true` in `gradle.properties`
2. Run `./gradlew clean`
3. Gradle reports configuration caching problem:
```
1 problem was found storing the configuration cache.
- Plugin 'nl.littlerobots.version-catalog-update': read system property 'reportfileName'
  See https://docs.gradle.org/7.3.3/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
```
```
org.gradle.api.InvalidUserCodeException: Read system property 'reportfileName'
	at org.gradle.configurationcache.SystemPropertyAccessListener.systemPropertyQueried(SystemPropertyAccessListener.kt:92)
	at org.gradle.internal.classpath.Instrumented$DecoratingProperties.getProperty(Instrumented.java:313)
	at org.gradle.internal.classpath.Instrumented$DecoratingProperties.getProperty(Instrumented.java:307)
	at org.gradle.internal.classpath.Instrumented$DecoratingProperties.get(Instrumented.java:327)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.get(DefaultGroovyMethods.java:8297)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask.getReportfileName(DependencyUpdatesTask.groovy:141)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask_Decorated.getReportfileName(Unknown Source)
	at nl.littlerobots.vcu.plugin.VersionCatalogUpdatePlugin$apply$1$dependencyUpdatesTask$1.execute(VersionCatalogUpdatePlugin.kt:56)
	at nl.littlerobots.vcu.plugin.VersionCatalogUpdatePlugin$apply$1$dependencyUpdatesTask$1.execute(VersionCatalogUpdatePlugin.kt:30)
        ...
```

**Comment by hvisser** [comment]
It looks like it's actually the versions plugin doing the reading, but triggered from the version catalog update plugin. I'll double check and see if there's a fix if that's the case.

**Comment by plnice** [comment]
Apparently this doesn't happen when using Gradle 7.4-rc-1 - most likely thanks to the automatic detection of system properties (https://docs.gradle.org/7.4-rc-1/release-notes.html#configuration-cache-improvements)

**Comment by hvisser** [comment]
I checked and the reading is indeed happening in the versions plugin. Since 7.4 will fix this, I think this issue can be closed. Feel free to reopen if you think otherwise.
